{application,n2o,
             [{description,"N2O MQTT TCP WebSocket"},
              {vsn,"8.11.0"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{n2o,[]}},
              {modules,[n2o,n2o_bert,n2o_cowboy,n2o_ftp,n2o_gproc,n2o_heart,
                        n2o_json,n2o_mqtt,n2o_multipart,n2o_pi,n2o_proto,
                        n2o_ring,n2o_secret,n2o_session,n2o_static,n2o_syn,
                        n2o_ws,n2o_xml]}]}.
